export const OWNER_TAX_POLICY = {
  en: 'Owners are independently responsible for registering themselves and their rental properties with the appropriate authorities, obtaining any required tax registrations, and filing and paying their own taxes under the rules that apply to their property and personal circumstances. IPM does not provide tax advice, select an owner’s tax status, or handle the owner’s independent registrations, returns, or tax obligations. We recommend working with your own accountant or qualified tax representative. IPM will coordinate with you to confirm the tax forms and documentation we need from you for our payment and reporting requirements. In the U.S., IPM provides Form 1099 where required. This document coordination does not replace your independent tax professional or transfer your tax responsibilities to IPM.',
  es: 'Cada propietario es responsable de registrar su actividad y sus propiedades de alquiler ante las autoridades correspondientes, obtener los registros fiscales necesarios y declarar y pagar sus propios impuestos conforme a las normas aplicables a su propiedad y situación personal. IPM no brinda asesoría fiscal, no elige la situación fiscal del propietario ni se encarga de sus registros, declaraciones u obligaciones fiscales independientes. Recomendamos trabajar con su propio contador o representante fiscal calificado. IPM coordinará con usted los formularios y documentos fiscales que necesitamos recibir para nuestros requisitos de pago e información. En Estados Unidos, IPM proporciona el Formulario 1099 cuando sea obligatorio. Esta coordinación documental no sustituye a su profesional fiscal ni transfiere sus responsabilidades fiscales a IPM.',
  vi: 'Chủ sở hữu tự chịu trách nhiệm đăng ký hoạt động và chỗ nghỉ cho thuê với cơ quan có thẩm quyền, hoàn thành các đăng ký thuế cần thiết, kê khai và nộp thuế theo quy định áp dụng cho chỗ nghỉ và hoàn cảnh cá nhân. IPM không tư vấn thuế, lựa chọn tình trạng thuế hay xử lý việc đăng ký, kê khai hoặc nghĩa vụ thuế riêng của chủ sở hữu. Chúng tôi khuyến nghị bạn làm việc với kế toán hoặc đại diện thuế đủ chuyên môn của riêng mình. IPM sẽ trao đổi với bạn để xác nhận các biểu mẫu và tài liệu thuế chúng tôi cần cho yêu cầu thanh toán và báo cáo. Tại Hoa Kỳ, IPM cung cấp Mẫu 1099 khi bắt buộc. Việc phối hợp tài liệu này không thay thế chuyên gia thuế độc lập hoặc chuyển trách nhiệm thuế của bạn sang IPM.',
}

export const OWNER_FAQ_CONTENT = {
  en: {
    title: 'Frequently Asked Questions for Property Owners & Managers',
    cta: 'Have a property with empty nights? Let IPM help you generate more reservations.',
    button: 'Get Started',
    items: [
      {
        id: 'promotion-fees',
        question: 'How does the 10% Listing Promotion plan or agreed nightly rate work?',
        answer: 'For Listing Promotion, you can choose 10% on reservations generated by IPM or an agreed guaranteed nightly rate. With the nightly-rate arrangement, you receive the agreed nightly amount and IPM may add a markup. IPM takes no commission on reservations you generate independently. There is no setup fee and no monthly subscription for the first two months.',
      },
      {
        id: 'full-management',
        question: 'How is 20% Full Management different from Listing Promotion?',
        answer: 'Full Management includes Listing Promotion plus guest communication and check-in coordination, cleaning and maintenance coordination, revenue optimization, owner support and monthly reporting, and multi-platform management. The advertised rate is 20% commission plus a monthly fee; confirm the specific charges and scope with IPM before starting. Both plans are available from the Services menu and Services page, with English and Spanish plan pages.',
      },
      {
        id: 'subscription',
        question: 'Does Listing Promotion have a monthly subscription?',
        answer: 'There is no monthly subscription during the first two months. From month three, Listing Promotion includes a $40 monthly subscription. When possible, this is deducted from IPM-generated reservation revenue. If that revenue is insufficient, you are not charged the subscription out of pocket. At the beginning of month three, review the results; if the service does not provide enough value, you can end it at no cost.',
      },
      {
        question: 'Do I have to stop using my Airbnb account?',
        answer: 'No. You can keep your current Airbnb listing and the reservations you already have. IPM can add your property to additional channels and connect the calendars. We coordinate secure co-host invitations or access instructions; do not send your Airbnb password through our forms or by email.',
      },
      {
        question: 'Which booking platforms can you list my property on?',
        answer: 'We can distribute your property across major booking channels such as Airbnb, Booking.com, Expedia and other available platforms, plus our direct booking channels. The goal is to put your empty nights in front of more travelers.',
      },
      {
        question: 'How do you prevent double bookings?',
        answer: 'We connect and sync the calendars across the platforms we manage. When a reservation comes in, those dates are blocked across the connected calendars so the same nights are not sold twice.',
      },
      {
        question: 'What if I don’t use a booking platform or I already have blocked dates?',
        answer: 'That is fine. You can send us your existing reservations and blocked dates by WhatsApp or email. We keep the master calendar updated. If you take a direct reservation later, simply send it to us so we can block those dates.',
      },
      {
        question: 'How quickly can my property be set up?',
        answer: 'Once we have the property information, photos, rates and availability, we can usually begin setting up the listings and connected calendars within a few days. You do not have to spend weeks learning each platform yourself.',
      },
      {
        question: 'Do I get access to see the reservations?',
        answer: 'Yes. You receive access to the IPM owner portal, where you can see the reservations we generate and follow your property activity. You can also receive notifications when new reservations come in.',
      },
      {
        question: 'Do I need professional photos?',
        answer: 'Professional photos are recommended because better photos can improve the listing, but they are not required to start. We can use your current photos first. If you want professional photos, we can also help check photographer options and pricing in your area.',
      },
      {
        id: 'tax-responsibility',
        question: 'Who handles my property registration, taxes, and tax documents?',
        answer: OWNER_TAX_POLICY.en,
      },
      {
        id: 'cancel',
        question: 'What happens if I want to cancel IPM services?',
        answer: 'IPM does not charge a cancellation fee. We just need to make sure any reservations already confirmed are properly handled. The goal is to keep the process simple and transparent for the owner.',
      },
    ],
  },
  es: {
    title: 'Preguntas Frecuentes para Propietarios y Administradores',
    cta: '¿Tiene noches disponibles en su propiedad? Deje que IPM le ayude a generar más reservaciones.',
    button: 'Comenzar',
    items: [
      {
        id: 'promotion-fees',
        question: '¿Cómo funciona el plan de Promoción de Anuncios del 10% o la tarifa nocturna acordada?',
        answer: 'En Promoción de Anuncios puede elegir pagar el 10% de las reservaciones generadas por IPM o acordar una tarifa nocturna garantizada. Con la tarifa nocturna, usted recibe el importe acordado e IPM puede añadir un margen. IPM no cobra comisión por las reservaciones que usted genere de forma independiente. No hay costo de configuración ni suscripción mensual durante los primeros dos meses.',
      },
      {
        id: 'full-management',
        question: '¿En qué se diferencia la Gestión Completa del 20% de la Promoción de Anuncios?',
        answer: 'La Gestión Completa incluye Promoción de Anuncios, comunicación con huéspedes y coordinación de check-in, coordinación de limpieza y mantenimiento, optimización de ingresos, soporte al propietario e informes mensuales y gestión multiplataforma. La tarifa anunciada es una comisión del 20% más una cuota mensual; confirme los cargos y el alcance con IPM antes de comenzar. Ambos planes están disponibles en el menú y la página de Servicios, con páginas en español e inglés.',
      },
      {
        id: 'subscription',
        question: '¿El plan de Promoción de Anuncios tiene una suscripción mensual?',
        answer: 'No hay suscripción mensual durante los primeros dos meses. Desde el tercer mes, Promoción de Anuncios incluye una suscripción de $40 al mes. Cuando sea posible, se descuenta de los ingresos de reservaciones generadas por IPM. Si esos ingresos no son suficientes, no se le cobra la suscripción de su bolsillo. Al inicio del tercer mes puede revisar los resultados y, si el servicio no aporta suficiente valor, terminarlo sin costo.',
      },
      {
        question: '¿Tengo que dejar de usar mi cuenta de Airbnb?',
        answer: 'No. Puede conservar su anuncio actual de Airbnb y las reservaciones que ya tiene. IPM puede agregar su propiedad a otras plataformas y conectar los calendarios. Coordinamos invitaciones seguras como coanfitrión o instrucciones de acceso; no envíe su contraseña de Airbnb mediante nuestros formularios ni por correo electrónico.',
      },
      {
        question: '¿En qué plataformas pueden publicar mi propiedad?',
        answer: 'Podemos distribuir su propiedad en plataformas principales como Airbnb, Booking.com, Expedia y otros canales disponibles, además de nuestros canales de reserva directa. La meta es mostrar sus noches vacías a más viajeros.',
      },
      {
        question: '¿Cómo evitan las reservaciones dobles?',
        answer: 'Conectamos y sincronizamos los calendarios de las plataformas que administramos. Cuando entra una reservación, esas fechas se bloquean en los calendarios conectados para evitar que las mismas noches se vendan dos veces.',
      },
      {
        question: '¿Qué pasa si no uso ninguna plataforma o ya tengo fechas bloqueadas?',
        answer: 'No hay problema. Puede enviarnos sus reservaciones actuales y fechas bloqueadas por WhatsApp o correo electrónico. Nosotros mantenemos el calendario principal actualizado. Si después recibe una reservación directa, solo nos avisa para bloquear esas fechas.',
      },
      {
        question: '¿Qué tan rápido pueden activar mi propiedad?',
        answer: 'Una vez que tengamos la información de la propiedad, fotos, tarifas y disponibilidad, normalmente podemos comenzar a configurar los anuncios y calendarios conectados en pocos días. Usted no tiene que pasar semanas aprendiendo cada plataforma.',
      },
      {
        question: '¿Tendré acceso para ver las reservaciones?',
        answer: 'Sí. Tendrá acceso al portal de propietarios de IPM, donde podrá ver las reservaciones que generamos y la actividad de su propiedad. También puede recibir notificaciones cuando entren nuevas reservaciones.',
      },
      {
        question: '¿Necesito fotos profesionales?',
        answer: 'Las fotos profesionales son recomendables porque pueden mejorar el anuncio, pero no son necesarias para comenzar. Podemos usar sus fotos actuales. Si desea fotos profesionales, también podemos ayudarle a revisar opciones y precios de fotógrafos en su zona.',
      },
      {
        id: 'tax-responsibility',
        question: '¿Quién se encarga del registro de mi propiedad, mis impuestos y los documentos fiscales?',
        answer: OWNER_TAX_POLICY.es,
      },
      {
        id: 'cancel',
        question: '¿Qué pasa si quiero cancelar los servicios de IPM?',
        answer: 'IPM no cobra una penalización por cancelar. Solo debemos asegurarnos de que las reservaciones que ya estén confirmadas se atiendan correctamente. La idea es mantener el proceso sencillo y transparente para el propietario.',
      },
    ],
  },
};

const FAQ_IDS = {
  common: ['promotion-fees', 'full-management', 'subscription', 'tax-responsibility', 'cancel'],
  listing: ['promotion-fees', 'subscription', 'tax-responsibility', 'cancel'],
  management: ['full-management', 'tax-responsibility', 'cancel'],
}

export const getOwnerFaqItems = (locale = 'en', plan = 'common') => {
  const content = OWNER_FAQ_CONTENT[locale === 'es' ? 'es' : 'en']
  const allowed = FAQ_IDS[plan] || FAQ_IDS.common
  return content.items.filter((item) => allowed.includes(item.id))
}