export const COPY = {
  en: {
    eyebrow: 'IPM PAYOUT CALCULATOR', title: 'Know what you’ll actually make from your booking',
    intro: 'Enter your rate, property location and booking channel to estimate guest cost, platform deductions, taxes and your potential owner payout.',
    calculate: 'Calculate my payout', free: 'Free to use. No signup required.',
    calcEyebrow: 'YOUR ESTIMATE', calcTitle: 'Short-Term Rental Payout Calculator',
    calcIntro: 'For any property owner, whether or not you are an IPM client. IPM fees are off by default and optional. Change any assumption to update the estimate, using your actual platform fees and local tax guidance.',
    ipmComparisonTitle: 'Compare with and without IPM',
    withoutIpm: 'Without IPM',
    withIpm: 'With IPM',
    ipmPreviewRate: 'Editable IPM comparison rate (%)',
    ipmPreviewNote: 'This comparison is optional. The main estimate uses the management option you select; no IPM fee is added by default. Target mode shows the nightly rate needed on each side. The 10% Listing Promotion fee applies only to IPM-generated reservations; confirm your agreement and any monthly fees.',
    timeSavingsTitle: 'Less manual work, more time for your property',
    timeSavingsCopy: 'IPM handles listing work and automations so you spend less time on manual updates, calendar coordination and follow-up. Depending on your plan, we also take on guest communication and management coordination. Our support is backed by 12 years of customer service experience. Time saved depends on your property, booking volume and selected plan.',
    knowRate: 'I know what I charge', knowPayout: 'I know what I want to make',
    where: 'Property location', country: 'Country', state: 'State', region: 'Province / region',
    county: 'County', city: 'City', localTax: 'Local lodging / occupancy tax rate', taxHelp: 'Tax rates can vary by state, county and city. Always verify your property’s local requirements.',
    unverified: 'No verified tax rate is configured for this location. Enter a rate from your local authority or tax professional; we will not guess.',
    platform: 'Booking channel', platformFee: 'Platform fee', feeHelp: 'This editable starting point is not a promise of your contracted fee.',
    reservation: 'Reservation details', nightly: 'Nightly rate', nights: 'Number of nights', cleaning: 'Cleaning fee', other: 'Other mandatory guest fees',
    target: 'Desired owner payout', targetHelp: 'This target is for the whole reservation, not a per-night amount.',
    processing: 'Payment processing', processingRate: 'Processing fee', fixed: 'Fixed processing fee',
    remit: 'Who remits the tax?', remitPlatform: 'Platform collects and remits it', remitOwner: 'Platform sends it to me; I remit it', remitSeparate: 'I collect / remit separately', remitUnsure: 'Not sure',
    management: 'IPM management', managed: 'Management option', none: 'No / OTA payout only', listing: 'IPM 10% Listing Promotion', full: 'IPM 20% Full Management', custom: 'Custom management %',
    customRate: 'Custom management rate', managementHelp: 'Management fees are shown separately from platform deductions. Confirm the basis in your agreement.',
    advanced: 'Advanced fee assumptions', advancedHelp: 'Default management fees use accommodation as their basis. Your agreement may use a different basis; confirm its terms. Other selected fee bases are estimates, not universal contract terms.',
    managementBasis: 'Management fee based on', platformBasis: 'Platform fee based on', processingBasis: 'Processing fee based on', accommodation: 'Accommodation', subtotal: 'Booking subtotal', guestTotalBasis: 'Guest total',
    taxable: 'Tax applies to', taxAccommodation: 'Accommodation', taxCleaning: 'Cleaning', taxOther: 'Other fees',
    result: 'Live payout breakdown', ownerPayout: 'Estimated owner payout', platformPayout: 'Estimated platform payout',
    bookingDetails: 'BOOKING DETAILS', payoutDetails: 'PAYOUT BREAKDOWN', nightlyResult: 'Nightly rate', nightsResult: 'Nights', accommodationResult: 'Accommodation',
    cleaningResult: 'Cleaning fee', otherResult: 'Other guest fees', subtotalResult: 'Booking subtotal', taxResult: 'Lodging tax', guestTotal: 'Estimated guest total',
    platformFeeResult: 'OTA / platform fee', processingResult: 'Payment processing', taxReserve: 'Tax held aside', managementResult: 'IPM management fee',
    ownerTaxNote: 'Tax is held aside as a reserve; confirm your actual remittance obligation.', platformTaxNote: 'Tax remitted by the platform is shown separately and is not deducted from rental revenue twice.',
    taxSeparateNote: 'Taxes collected separately are included in the estimated guest total, but are excluded from platform payout and owner profit.',
    taxUnsureNote: 'Because the tax remitter is not confirmed, tax is conservatively included in the transfer and held aside as a reserve—not counted as owner profit.',
    reverseTitle: 'Rate needed for your target', requiredRate: 'Required nightly rate', requiredSubtotal: 'Required booking subtotal', increase: 'Rate increase required',
    copy: 'Copy results', copySuccess: 'Estimate copied to clipboard.', copyError: 'Could not access clipboard. Select and copy the estimate below.', copyInvalid: 'Complete the required fields before copying the estimate.', copiedFallback: 'Copy this estimate manually:',
    compare: 'Compare platforms', compareIntro: 'Compare channels with the same reservation assumptions. Fees remain editable and missing contracted fees must be entered.',
    hideCompare: 'Hide comparison', showCompare: 'Compare platforms', yourFee: 'Your platform fee (%)', guestFee: 'Guest-side fee (%)', compareGuestFeeHelp: 'Each channel has its own guest-side fee; comparison defaults to 0%.', comparisonPayout: 'Estimated payout', highest: 'Highest estimate', winnerNote: 'This is only the highest estimate under the assumptions entered—not a recommendation or claim that the channel is best.',
    comparePerformance: 'Actual performance also depends on demand, occupancy, average daily rate, conversion, payment costs and other factors.',
    presetNote: 'Starting estimate only. Your actual fee may vary; confirm the fee shown in your platform account.',
    bookingNote: 'Example rate — replace with your contracted Booking.com commission.',
    expediaNote: 'Expedia compensation is contract-specific. Enter the actual rate from your agreement.',
    vrboNote: 'Vrbo fee structures vary by account type, software connection, region and payment setup.',
    googleNote: 'Free Google Vacation Rental booking links do not charge an OTA referral commission. Booking-engine, processing, management and tax expenses may still apply.',
    directNote: 'Direct booking has no OTA commission here; processing, booking-engine, tax and management expenses may still apply.',
    financialEducation: 'Fee math, without the guesswork', educationIntro: 'A platform fee and the price increase needed to offset it are not the same percentage.',
    markupTitle: 'A 15.5% platform fee does not mean you raise your price 15.5%',
    wrong: 'If you add the fee percentage, the deduction still leaves a shortfall.', correct: 'To net the target after a percentage fee, divide by what remains after the fee.',
    wants: 'Owner wants to receive', wrongMethod: 'Wrong: add 15.5%', afterFee: 'Net after 15.5% fee', stillShort: 'Still short of target', rightMethod: 'Correct: divide by 0.845', feeAmount: 'Platform fee', markup: 'Required markup', formula: 'Required markup % = (1 ÷ (1 − fee rate)) − 1',
    quickTitle: 'Quick fee reference', quickCaption: 'Required charge to receive 250 currency units after the listed platform fee',
    feeColumn: 'Fee', priceColumn: 'Required price', markupColumn: 'Markup',
    channelsTitle: 'Understanding each booking channel', channelsIntro: 'Contract terms, account settings and payment flows matter. These examples are educational; verify your current terms.',
    airbnbText: 'Airbnb is moving software-connected hosts to its single host service fee model. Many hosts on this model pay around 15.5%; Mexico and Brazil use a 16% single fee. The actual fee may differ by account. Confirm the rate shown in your Airbnb account.',
    vrboText: 'Vrbo fee structures vary. Traditional pay-per-booking arrangements can include platform commission and payment processing, while software-integrated properties can have different arrangements. Enter your actual fee.',
    bookingText: 'Booking.com commission is determined by each property’s contract; there is no single rate for every property. Statements may also include payment charges, VAT, taxes, withholding or other charges. Replace any example with your contracted rate.',
    expediaText: 'Expedia Group compensation varies by property agreement and payment / collection model. Use the percentage and payout basis in your own agreement.',
    googleText: 'Google free booking links can refer travelers to a property’s booking site without an OTA booking or referral commission. Payment processing, booking engine, management, taxes and operating expenses may still apply.',
    directText: 'Direct reservations avoid an OTA platform commission in this estimate. They can still involve card processing, booking-engine fees, taxes, management and operating expenses; do not assume every direct booking is more profitable.',
    exampleOnly: 'EXAMPLE ONLY', requiredExample: 'Required charge', markupExample: 'Required markup', mexicoExample: 'Mexico at 16%',
    ipmTitle: 'Why IPM uses multi-channel distribution', ipmText: 'A property’s best strategy does not always mean choosing one booking platform. Channels can differ in fees, guest audiences, demand, booking behavior, cancellation policies and average booking values. IPM helps owners expand distribution while keeping availability synchronized across supported channels. That helps reduce double-booking risk and lets owners evaluate reservations by actual revenue—not just the advertised nightly rate.',
    plansTitle: 'Two ways IPM supports owners', listingTitle: 'Listing Promotion', fullTitle: 'Full Management',
    listingDesc: 'No upfront setup cost. Keep your existing Airbnb listing while IPM promotes and distributes your property through additional supported channels. Calendars can be synchronized to help prevent double bookings. IPM charges 10% on reservations generated through our program.',
    fullDesc: '20% commission plus a monthly fee. Includes Listing Promotion, plus guest communication and check-in coordination, cleaning and maintenance coordination, revenue optimization strategy, owner support and monthly reporting, and multi-platform management and updates.',
    exploreListing: 'Explore 10% Listing Promotion', exploreFull: 'Explore 20% Full Management',
    ctaTitle: 'Want IPM to help increase your property’s distribution?', ctaText: 'Keep control of your property while expanding where travelers can find and book it.', cta: 'Explore IPM Listing Promotion',
    sources: 'Sources & references', updated: 'Last updated: October 2026',
    disclaimer: 'Platform fees, payment-processing charges, taxes and payout methods can vary by property, account, location, contract and reservation. Estimates provided by the IPM Payout Calculator are for informational purposes only and are not tax, accounting or legal advice. Always verify your platform fees and local tax obligations.',
    manualSource: 'Tax rate entered manually. Verify this figure with the relevant local authority.',
    verifiedSource: 'Verified tax configuration', taxName: 'Tax', taxVerified: 'Last verified',
    basisNote: 'Taxes held aside are not profit. Estimates exclude subscriptions/monthly fees, operating costs, withholding, and any separate VAT on commissions or payment charges unless explicitly included in your inputs. These are not a tax determination.',
    guestFeeHelp: 'Default 0%. This adds to the guest total, not owner revenue. Enter an actual guest-side service charge only when it applies; single-fee hosts generally leave this at zero.',
    explainAdd: 'Simply adding the fee percentage does not account for the fee being deducted from the higher price.',
    summaryTitle: 'IPM Payout Estimate', summaryPlatform: 'Platform', summaryNightly: 'Nightly Rate', summaryTarget: 'Desired Owner Payout', summaryNights: 'Nights',
    summaryAccommodation: 'Accommodation', summaryCleaning: 'Cleaning', summaryOther: 'Other fees', summaryFee: 'Platform Fee',
    summaryFeeAmount: 'Estimated Platform Fee', summaryPayout: 'Estimated Owner Payout', summaryLocation: 'Property Location',
    summaryTax: 'Estimated Lodging Tax', summaryUnavailable: 'Not specified', summaryOnly: 'Estimated calculation only.',
  },
  es: {
    eyebrow: 'CALCULADORA DE PAGOS IPM', title: 'Sepa cuánto recibirá realmente por su reserva',
    intro: 'Ingrese su tarifa, ubicación y canal de reserva para estimar el costo para el huésped, las deducciones de la plataforma, los impuestos y su posible pago como propietario.',
    calculate: 'Calcular mi pago', free: 'Gratis. No requiere registro.',
    calcEyebrow: 'SU ESTIMACIÓN', calcTitle: 'Calculadora de Pagos de Alquileres Vacacionales',
    calcIntro: 'Para cualquier propietario, sea o no cliente de IPM. Las comisiones de IPM son opcionales y están desactivadas por defecto. Cambie los supuestos para actualizar la estimación, usando sus comisiones reales y la orientación fiscal local.',
    ipmComparisonTitle: 'Compare con y sin IPM',
    withoutIpm: 'Sin IPM',
    withIpm: 'Con IPM',
    ipmPreviewRate: 'Comisión editable para comparar con IPM (%)',
    ipmPreviewNote: 'Esta comparación es opcional. La estimación principal usa la opción de gestión que seleccione; no se añade comisión de IPM por defecto. El modo objetivo muestra la tarifa necesaria en cada caso. El 10% de Promoción de Anuncios solo aplica a reservas generadas por IPM; confirme su contrato y las cuotas mensuales.',
    timeSavingsTitle: 'Menos trabajo manual y más tiempo para su propiedad',
    timeSavingsCopy: 'IPM se encarga del trabajo de los anuncios y sus automatizaciones, para que dedique menos tiempo a actualizaciones manuales, coordinación de calendarios y seguimiento. Según su plan, también asumimos la comunicación con huéspedes y la coordinación de gestión. Nuestro soporte cuenta con 12 años de experiencia en atención al cliente. El tiempo ahorrado depende de su propiedad, el volumen de reservas y el plan elegido.',
    knowRate: 'Sé cuánto cobro', knowPayout: 'Sé cuánto quiero recibir',
    where: 'Ubicación de la propiedad', country: 'País', state: 'Estado', region: 'Provincia / región',
    county: 'Condado', city: 'Ciudad', localTax: 'Tasa local de alojamiento / ocupación', taxHelp: 'Las tasas pueden variar por estado, condado y ciudad. Verifique siempre los requisitos locales de su propiedad.',
    unverified: 'No hay una tasa verificada configurada para esta ubicación. Ingrese una tasa de la autoridad local o de un profesional fiscal; no haremos suposiciones.',
    platform: 'Canal de reserva', platformFee: 'Comisión de plataforma', feeHelp: 'Este valor inicial editable no garantiza la comisión de su contrato.',
    reservation: 'Datos de la reserva', nightly: 'Tarifa por noche', nights: 'Número de noches', cleaning: 'Tarifa de limpieza', other: 'Otros cargos obligatorios al huésped',
    target: 'Pago deseado al propietario', targetHelp: 'Este objetivo corresponde a toda la reserva, no a una tarifa por noche.',
    processing: 'Procesamiento de pagos', processingRate: 'Comisión de procesamiento', fixed: 'Cargo fijo de procesamiento',
    remit: '¿Quién remite el impuesto?', remitPlatform: 'La plataforma lo cobra y remite', remitOwner: 'La plataforma me lo envía y yo lo remito', remitSeparate: 'Lo cobro / remito por separado', remitUnsure: 'No estoy seguro',
    management: 'Gestión IPM', managed: 'Opción de gestión', none: 'No / solo pago de la OTA', listing: 'Promoción de Anuncios IPM 10%', full: 'Gestión Completa IPM 20%', custom: 'Porcentaje de gestión personalizado',
    customRate: 'Tasa de gestión personalizada', managementHelp: 'Las tarifas de gestión aparecen separadas de las deducciones de la plataforma. Verifique la base de cálculo en su acuerdo.',
    advanced: 'Supuestos avanzados de tarifas', advancedHelp: 'Por defecto, las tarifas de gestión se calculan sobre el alojamiento. Su contrato puede usar otra base; verifique sus términos. Las demás bases son supuestos, no términos contractuales universales.',
    managementBasis: 'Base de tarifa de gestión', platformBasis: 'Base de tarifa de plataforma', processingBasis: 'Base de procesamiento', accommodation: 'Alojamiento', subtotal: 'Subtotal de reserva', guestTotalBasis: 'Total del huésped',
    taxable: 'El impuesto aplica a', taxAccommodation: 'Alojamiento', taxCleaning: 'Limpieza', taxOther: 'Otros cargos',
    result: 'Desglose actualizado', ownerPayout: 'Pago estimado al propietario', platformPayout: 'Pago estimado de la plataforma',
    bookingDetails: 'DETALLES DE LA RESERVA', payoutDetails: 'DESGLOSE DEL PAGO', nightlyResult: 'Tarifa por noche', nightsResult: 'Noches', accommodationResult: 'Alojamiento',
    cleaningResult: 'Limpieza', otherResult: 'Otros cargos al huésped', subtotalResult: 'Subtotal de reserva', taxResult: 'Impuesto de alojamiento', guestTotal: 'Total estimado del huésped',
    platformFeeResult: 'Comisión de OTA / plataforma', processingResult: 'Procesamiento de pagos', taxReserve: 'Impuesto reservado', managementResult: 'Tarifa de gestión IPM',
    ownerTaxNote: 'El impuesto se reserva aparte; confirme su obligación real de remisión.', platformTaxNote: 'El impuesto remitido por la plataforma aparece por separado y no se deduce dos veces de los ingresos de alojamiento.',
    taxSeparateNote: 'Los impuestos cobrados por separado se incluyen en el total estimado del huésped, pero se excluyen del pago de la plataforma y de las ganancias del propietario.',
    taxUnsureNote: 'Como no se confirmó quién remite el impuesto, se incluye de forma conservadora en la transferencia y se reserva; no se cuenta como ganancia.',
    reverseTitle: 'Tarifa necesaria para su objetivo', requiredRate: 'Tarifa por noche necesaria', requiredSubtotal: 'Subtotal de reserva necesario', increase: 'Aumento de tarifa requerido',
    copy: 'Copiar resultados', copySuccess: 'Estimación copiada.', copyError: 'No se pudo acceder al portapapeles. Seleccione y copie el resumen.', copyInvalid: 'Complete los campos obligatorios antes de copiar la estimación.', copiedFallback: 'Copie esta estimación manualmente:',
    compare: 'Comparar plataformas', compareIntro: 'Compare canales con los mismos supuestos de reserva. Las tarifas son editables y debe ingresar las comisiones contractuales que falten.',
    hideCompare: 'Ocultar comparación', showCompare: 'Comparar plataformas', yourFee: 'Su tarifa de plataforma (%)', guestFee: 'Comisión para el huésped (%)', compareGuestFeeHelp: 'Cada canal tiene su propia comisión para el huésped; la comparación empieza en 0%.', comparisonPayout: 'Pago estimado', highest: 'Estimación más alta', winnerNote: 'Esta es solo la estimación más alta con los supuestos ingresados; no es una recomendación ni afirma que el canal sea mejor.',
    comparePerformance: 'El rendimiento real también depende de la demanda, ocupación, tarifa diaria promedio, conversión, costos de pago y otros factores.',
    presetNote: 'Solo una estimación inicial. Su comisión real puede variar; confirme la tarifa en su cuenta.',
    bookingNote: 'Tarifa de ejemplo: reemplácela con la comisión contratada de Booking.com.',
    expediaNote: 'Solo como ejemplo. La compensación de Expedia depende del contrato.',
    vrboNote: 'Las tarifas de Vrbo varían según el tipo de cuenta, conexión de software, región y configuración de pagos.',
    googleNote: 'Los enlaces gratuitos de Google Vacation Rentals no cobran comisión de referencia de OTA. Aún pueden existir costos de motor de reservas, procesamiento, gestión e impuestos.',
    directNote: 'La reserva directa no tiene comisión de OTA en este cálculo; aún puede haber costos de procesamiento, motor de reservas, impuestos y gestión.',
    financialEducation: 'La matemática de las comisiones, sin conjeturas', educationIntro: 'La comisión de una plataforma y el aumento necesario para compensarla no son el mismo porcentaje.',
    markupTitle: 'Una comisión de plataforma del 15.5% no significa subir el precio un 15.5%',
    wrong: 'Si suma el porcentaje de comisión, la deducción todavía deja una diferencia.', correct: 'Para recibir el objetivo después de una comisión porcentual, divida entre lo que queda.',
    wants: 'El propietario quiere recibir', wrongMethod: 'Incorrecto: sumar 15.5%', afterFee: 'Neto tras comisión del 15.5%', stillShort: 'Aún falta para el objetivo', rightMethod: 'Correcto: dividir entre 0.845', feeAmount: 'Comisión de plataforma', markup: 'Margen necesario', formula: 'Margen necesario % = (1 ÷ (1 − tasa de comisión)) − 1',
    quickTitle: 'Referencia rápida de comisiones', quickCaption: 'Cargo necesario para recibir 250 unidades de moneda después de la comisión indicada',
    feeColumn: 'Comisión', priceColumn: 'Precio requerido', markupColumn: 'Margen',
    channelsTitle: 'Conozca cada canal de reserva', channelsIntro: 'Los contratos, la configuración de la cuenta y los flujos de pago importan. Estos ejemplos son educativos; verifique sus términos actuales.',
    airbnbText: 'Airbnb está migrando a los anfitriones conectados por software a un modelo de tarifa única para anfitriones. Muchos anfitriones de este modelo pagan alrededor del 15.5%; México y Brasil usan una tarifa única del 16%. La comisión real puede variar según la cuenta. Confirme la tarifa en su cuenta de Airbnb.',
    vrboText: 'Las tarifas de Vrbo varían. Los acuerdos tradicionales por reserva pueden incluir comisión de plataforma y procesamiento; las propiedades conectadas por software pueden tener otros acuerdos. Ingrese su tarifa real.',
    bookingText: 'La comisión de Booking.com se determina por contrato de cada propiedad; no hay una tasa única para todos. Los estados también pueden incluir cargos de pago, IVA, impuestos, retenciones u otros cargos. Reemplace cualquier ejemplo con su tarifa contratada.',
    expediaText: 'La compensación de Expedia Group varía según el acuerdo de la propiedad y el modelo de pago o cobro. Use el porcentaje y la base de pago de su contrato.',
    googleText: 'Los enlaces gratuitos de Google pueden dirigir al viajero al sitio de reservas de la propiedad sin cobrar una comisión de reserva o referencia de OTA. Aún pueden aplicarse procesamiento, motor de reservas, gestión, impuestos y gastos operativos.',
    directText: 'Las reservas directas evitan una comisión de plataforma OTA en este cálculo. Aún pueden incluir procesamiento de tarjeta, motor de reservas, impuestos, gestión y gastos operativos; no suponga que toda reserva directa es más rentable.',
    exampleOnly: 'SOLO COMO EJEMPLO', requiredExample: 'Cargo requerido', markupExample: 'Margen requerido', mexicoExample: 'México al 16%',
    ipmTitle: 'Por qué IPM usa distribución multicanal', ipmText: 'La mejor estrategia de una propiedad no siempre consiste en elegir una sola plataforma. Los canales pueden diferir en comisiones, público, demanda, comportamiento de reserva, políticas de cancelación y valor promedio de reserva. IPM ayuda a ampliar la distribución y sincronizar la disponibilidad entre canales compatibles. Esto ayuda a reducir el riesgo de reservas duplicadas y permite evaluar cada reserva por sus ingresos reales, no solo por la tarifa anunciada por noche.',
    plansTitle: 'Dos formas en que IPM apoya a propietarios', listingTitle: 'Promoción de Anuncios', fullTitle: 'Gestión Completa',
    listingDesc: 'Sin costo inicial de configuración. Mantenga su anuncio actual de Airbnb mientras IPM promociona y distribuye su propiedad en canales compatibles adicionales. Los calendarios pueden sincronizarse para ayudar a prevenir reservas duplicadas. IPM cobra el 10% de las reservas generadas mediante nuestro programa.',
    fullDesc: 'Incluye Promoción de Anuncios, además de comunicación con huéspedes y coordinación de check-in, coordinación de limpieza y mantenimiento, estrategia de optimización de ingresos, soporte e informes mensuales y gestión y actualizaciones multiplataforma.',
    exploreListing: 'Conozca Promoción de Anuncios 10%', exploreFull: 'Conozca Gestión Completa 20%',
    ctaTitle: '¿Quiere que IPM ayude a ampliar la distribución de su propiedad?', ctaText: 'Mantenga el control de su propiedad y amplíe dónde los viajeros pueden encontrarla y reservarla.', cta: 'Conozca Promoción de Anuncios IPM',
    sources: 'Fuentes y referencias', updated: 'Última actualización: octubre de 2026',
    disclaimer: 'Las tarifas de plataforma, cargos por procesamiento, impuestos y métodos de pago pueden variar según la propiedad, cuenta, ubicación, contrato y reserva. Las estimaciones de la Calculadora de Pagos IPM son solo informativas y no constituyen asesoría fiscal, contable ni legal. Verifique siempre las tarifas de su plataforma y sus obligaciones fiscales locales.',
    manualSource: 'Tasa ingresada manualmente. Verifique esta cifra con la autoridad local correspondiente.',
    verifiedSource: 'Configuración fiscal verificada', taxName: 'Impuesto', taxVerified: 'Verificado',
    basisNote: 'Los impuestos reservados no son ganancias. La estimación excluye suscripciones/cuotas mensuales, gastos operativos, retenciones e IVA adicional sobre comisiones o cargos de pago, salvo que los incluya en los valores ingresados. No es una determinación fiscal.',
    guestFeeHelp: 'Predeterminado 0%. Se suma al total del huésped, no a los ingresos del propietario. Ingrese un cargo real al huésped solo si aplica; los anfitriones con tarifa única normalmente dejan cero.',
    explainAdd: 'Sumar la comisión de la plataforma no considera que esta se deduce del precio más alto.',
    summaryTitle: 'Estimación de pago IPM', summaryPlatform: 'Plataforma', summaryNightly: 'Tarifa por noche', summaryTarget: 'Pago deseado al propietario', summaryNights: 'Noches',
    summaryAccommodation: 'Alojamiento', summaryCleaning: 'Limpieza', summaryOther: 'Otros cargos', summaryFee: 'Comisión de plataforma',
    summaryFeeAmount: 'Comisión estimada de plataforma', summaryPayout: 'Pago estimado al propietario', summaryLocation: 'Ubicación de la propiedad',
    summaryTax: 'Impuesto de alojamiento estimado', summaryUnavailable: 'No especificada', summaryOnly: 'Cálculo estimado únicamente.',
  },
}

export const SOURCES = [
  ['Airbnb Host Service Fees', 'https://www.airbnb.com/help/article/1857'],
  ['Airbnb Single Fee Update', 'https://www.airbnb.com/resources/hosting-homes/a/simplifying-airbnb-service-fees-746'],
  ['Airbnb Tax Collection', 'https://www.airbnb.com/help/article/1036'],
  ['Vrbo pay-per-booking fees', 'https://help.vrbo.com/articles/How-is-the-booking-fee-calculated'],
  ['Vrbo integration information', 'https://help.vrbo.com/articles/About-Vrbo-integration'],
  ['Booking.com Payments API: payments and payouts', 'https://developers.booking.com/connectivity/docs/payments-api/managing-payment-and-payout-details'],
  ['Booking.com partner commission guidance', 'https://partner.booking.com/en-gb/payments'],
  ['Expedia Group property management docs', 'https://developers.expediagroup.com/supply/lodging/docs/property_mgmt_apis/product/learn'],
  ['Expedia Group partner resources', 'https://partner.expediagroup.com/'],
  ['Google Vacation Rental brands: no referral commissions', 'https://support.google.com/hotelprices/answer/13449281?hl=en'],
  ['Google free booking links', 'https://support.google.com/hotelprices/answer/10472394?hl=en'],
]

const SPANISH_ERRORS = {
  'Enter a valid non-negative number.': 'Ingrese un número válido mayor o igual a cero.',
  'Enter a percentage from 0 to less than 100.': 'Ingrese un porcentaje de 0 a menos de 100.',
  'Enter a whole number of nights from 1 to 3650.': 'Ingrese un número entero de noches entre 1 y 3650.',
  'Enter an amount no greater than 1,000,000,000.': 'Ingrese un importe no superior a 1.000.000.000.',
  'Choose a calculator mode.': 'Seleccione un modo de cálculo.',
  'Choose a valid fee basis.': 'Seleccione una base de comisión válida.',
  'Choose who remits the tax.': 'Seleccione quién declara y paga el impuesto.',
  'Choose valid taxable components.': 'Seleccione los conceptos sujetos al impuesto.',
  'These combined deductions leave no positive revenue. Reduce the fees to calculate a target rate.': 'Las deducciones combinadas no dejan ingresos positivos. Reduzca las comisiones para calcular una tarifa objetivo.',
  'The fixed guest fees already exceed this target at a zero nightly rate. Reduce those fees or increase your target.': 'Los cargos fijos al huésped ya superan este objetivo con una tarifa de cero. Reduzca esos cargos o aumente su objetivo.',
  'The required nightly rate is outside the supported range. Reduce the target or fees.': 'La tarifa necesaria está fuera del rango permitido. Reduzca el objetivo o las comisiones.',
  'This target cannot be reached within the supported nightly-rate range.': 'No se puede alcanzar este objetivo dentro del rango de tarifas permitido.',
}

export function localizePayoutError(message, language) {
  return language === 'es' ? SPANISH_ERRORS[message] || 'Revise los importes y las comisiones ingresados.' : message
}
